version: '3.8'

services:
  backend:
    container_name: backend
    build: ./cp_api
    command: gunicorn cp_api.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./cp_api/:/usr/src/app/
      - ./cp_api/static:/static
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./cp_ui/Dockerfile
    # command: /start.sh
    volumes:
      - build:/app/build

  nginx:
    restart: unless-stopped
    container_name: nginx_server
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./cp_api/static:/static
      - build:/app/build

volumes:
  postgres_data:
  build:


# https://saasitive.com/tutorial/docker-compose-django-react-nginx-let-s-encrypt/
