version: '3.8'

services:
  backend:
    container_name: backend
    build: ./cp_api
    command: gunicorn cp_api.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./cp_api/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./cp_ui/Dockerfile
    command: /start.sh
    expose:
      - 3000

  nginx:
    restart: unless-stopped
    container_name: nginx_server
    build: ./nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

volumes:
  postgres_data:



# https://saasitive.com/tutorial/docker-compose-django-react-nginx-let-s-encrypt/
