# Generated by Django 3.2.3 on 2021-05-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210527_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='subject',
            new_name='subjects',
        ),
    ]
