# Generated by Django 3.2.3 on 2021-05-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_subject_lesson_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='staff',
            name='summary',
        ),
        migrations.CreateModel(
            name='SummaryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.language')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='backend.summary')),
            ],
        ),
    ]
