# Generated by Django 3.2.3 on 2021-05-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210529_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='backend.summary'),
        ),
    ]
