# Generated by Django 3.2.3 on 2021-05-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_staff_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='edition',
            new_name='editions',
        ),
        migrations.AlterField(
            model_name='summarylanguage',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='backend.summary'),
        ),
    ]
