# Generated by Django 4.1.7 on 2023-03-31 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210529_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarylanguage',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='backend.summary'),
        ),
    ]
