# Generated by Django 4.2.1 on 2023-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_summarylanguage_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='link',
            field=models.URLField(max_length=128, null=True),
        ),
    ]
