# Generated by Django 4.2.3 on 2023-07-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_activity_scheduledata_scheduledatalanguage_schedule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='time_ends',
            new_name='time_end',
        ),
    ]
